// Mock Dubai property dataset for the Agent Hub MVP.
// Realistic-but-fictional listings across six well-known areas.
// Images are served by picsum.photos with a stable seed per property so they
// don't reshuffle on every refresh.

function img(seed) {
  return `https://picsum.photos/seed/${seed}/600/360`;
}

export const PROPERTIES = [
  // ----- Dubai Marina -----
  {
    id: "p_marina_01",
    title: "2BR with Full Marina View",
    type: "apartment",
    listing: "sale",
    price: 2150000,
    beds: 2,
    baths: 2,
    area_sqft: 1240,
    building: "Marina Heights Tower 1",
    area: "Dubai Marina",
    lat: 25.0791,
    lng: 55.1390,
    image: img("p_marina_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 123 4567",
    features: ["Marina view", "Furnished", "Parking", "Pool", "Gym"],
    yearBuilt: 2018,
    status: "available",
  },
  {
    id: "p_marina_02",
    title: "1BR Cozy near Marina Walk",
    type: "apartment",
    listing: "rent",
    price: 95000,
    beds: 1,
    baths: 1,
    area_sqft: 760,
    building: "Princess Tower",
    area: "Dubai Marina",
    lat: 25.0803,
    lng: 55.1437,
    image: img("p_marina_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 234 5678",
    features: ["Partial sea view", "Furnished", "Walk to metro"],
    yearBuilt: 2012,
    status: "available",
  },
  {
    id: "p_marina_03",
    title: "Penthouse 4BR Sky Suite",
    type: "penthouse",
    listing: "sale",
    price: 9500000,
    beds: 4,
    baths: 5,
    area_sqft: 4100,
    building: "Cayan Tower",
    area: "Dubai Marina",
    lat: 25.0823,
    lng: 55.1398,
    image: img("p_marina_03"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 345 6789",
    features: ["Floor-to-ceiling glass", "Private terrace", "3 parking", "Skyline view"],
    yearBuilt: 2014,
    status: "available",
  },
  {
    id: "p_marina_04",
    title: "Studio Investor Special",
    type: "studio",
    listing: "sale",
    price: 850000,
    beds: 0,
    baths: 1,
    area_sqft: 480,
    building: "Marina Diamond 4",
    area: "Dubai Marina",
    lat: 25.0775,
    lng: 55.1422,
    image: img("p_marina_04"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 456 7890",
    features: ["High ROI", "Tenanted", "Near tram"],
    yearBuilt: 2010,
    status: "available",
  },

  // ----- Downtown Dubai -----
  {
    id: "p_downtown_01",
    title: "Burj View 2BR — Premium Finish",
    type: "apartment",
    listing: "sale",
    price: 3950000,
    beds: 2,
    baths: 3,
    area_sqft: 1485,
    building: "Burj Vista 1",
    area: "Downtown Dubai",
    lat: 25.1958,
    lng: 55.2761,
    image: img("p_downtown_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 111 2222",
    features: ["Burj Khalifa view", "Branded finishings", "Concierge", "Pool"],
    yearBuilt: 2019,
    status: "available",
  },
  {
    id: "p_downtown_02",
    title: "Spacious 3BR Family Apartment",
    type: "apartment",
    listing: "rent",
    price: 245000,
    beds: 3,
    baths: 4,
    area_sqft: 2100,
    building: "The Address Residences",
    area: "Downtown Dubai",
    lat: 25.1933,
    lng: 55.2728,
    image: img("p_downtown_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 222 3333",
    features: ["Hotel services", "Fountain view", "Maid's room"],
    yearBuilt: 2017,
    status: "available",
  },
  {
    id: "p_downtown_03",
    title: "1BR City Walk — Modern",
    type: "apartment",
    listing: "sale",
    price: 1850000,
    beds: 1,
    baths: 2,
    area_sqft: 860,
    building: "City Walk Building 4",
    area: "Downtown Dubai",
    lat: 25.2061,
    lng: 55.2628,
    image: img("p_downtown_03"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 333 4444",
    features: ["Walking district", "Boutique retail downstairs", "Smart home"],
    yearBuilt: 2020,
    status: "available",
  },
  {
    id: "p_downtown_04",
    title: "Off-Plan 1BR — Handover 2026",
    type: "apartment",
    listing: "sale",
    price: 1650000,
    beds: 1,
    baths: 1,
    area_sqft: 780,
    building: "Forte 2",
    area: "Downtown Dubai",
    lat: 25.1979,
    lng: 55.2702,
    image: img("p_downtown_04"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 444 5555",
    features: ["Payment plan 60/40", "Post-handover plan", "Opera district"],
    yearBuilt: 2026,
    status: "available",
  },

  // ----- Business Bay -----
  {
    id: "p_bb_01",
    title: "2BR Canal View — High Floor",
    type: "apartment",
    listing: "sale",
    price: 2750000,
    beds: 2,
    baths: 3,
    area_sqft: 1320,
    building: "Damac Maison Bay's Edge",
    area: "Business Bay",
    lat: 25.1862,
    lng: 55.2615,
    image: img("p_bb_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 555 6666",
    features: ["Canal view", "Hotel pool access", "Furnished"],
    yearBuilt: 2018,
    status: "available",
  },
  {
    id: "p_bb_02",
    title: "Studio Investment Unit — Yielding 8%",
    type: "studio",
    listing: "sale",
    price: 720000,
    beds: 0,
    baths: 1,
    area_sqft: 420,
    building: "Executive Bay",
    area: "Business Bay",
    lat: 25.1832,
    lng: 55.2587,
    image: img("p_bb_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 666 7777",
    features: ["Tenanted", "8% gross yield", "Easy exit"],
    yearBuilt: 2014,
    status: "available",
  },
  {
    id: "p_bb_03",
    title: "1BR Modern — Short-Term Friendly",
    type: "apartment",
    listing: "rent",
    price: 110000,
    beds: 1,
    baths: 2,
    area_sqft: 820,
    building: "DAMAC Towers by Paramount",
    area: "Business Bay",
    lat: 25.1875,
    lng: 55.2671,
    image: img("p_bb_03"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 777 8888",
    features: ["Branded interiors", "Short-term let allowed", "Concierge"],
    yearBuilt: 2019,
    status: "available",
  },
  {
    id: "p_bb_04",
    title: "Office Space — Grade A",
    type: "office",
    listing: "rent",
    price: 220000,
    beds: 0,
    baths: 2,
    area_sqft: 1850,
    building: "Bay Square Building 5",
    area: "Business Bay",
    lat: 25.1885,
    lng: 55.2654,
    image: img("p_bb_04"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 888 9999",
    features: ["Fitted out", "Glass partitions", "Parking allocations"],
    yearBuilt: 2015,
    status: "available",
  },

  // ----- JVC (Jumeirah Village Circle) -----
  {
    id: "p_jvc_01",
    title: "1BR Affordable Starter",
    type: "apartment",
    listing: "sale",
    price: 780000,
    beds: 1,
    baths: 2,
    area_sqft: 760,
    building: "Belgravia 2",
    area: "JVC",
    lat: 25.0529,
    lng: 55.2071,
    image: img("p_jvc_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 121 2121",
    features: ["First-time buyer friendly", "Family community", "Park nearby"],
    yearBuilt: 2017,
    status: "available",
  },
  {
    id: "p_jvc_02",
    title: "2BR + Maid Family Apartment",
    type: "apartment",
    listing: "rent",
    price: 95000,
    beds: 2,
    baths: 3,
    area_sqft: 1180,
    building: "Bloom Heights",
    area: "JVC",
    lat: 25.0481,
    lng: 55.2104,
    image: img("p_jvc_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 131 3131",
    features: ["Maid's room", "Built-in kitchen", "Quiet street"],
    yearBuilt: 2020,
    status: "available",
  },
  {
    id: "p_jvc_03",
    title: "3BR Townhouse — Garden",
    type: "townhouse",
    listing: "sale",
    price: 2850000,
    beds: 3,
    baths: 4,
    area_sqft: 2100,
    building: "Nakheel Townhouses",
    area: "JVC",
    lat: 25.0503,
    lng: 55.2042,
    image: img("p_jvc_03"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 141 4141",
    features: ["Private garden", "2 parking", "Community pool"],
    yearBuilt: 2019,
    status: "available",
  },
  {
    id: "p_jvc_04",
    title: "Studio Off-Plan — Payment Plan",
    type: "studio",
    listing: "sale",
    price: 590000,
    beds: 0,
    baths: 1,
    area_sqft: 410,
    building: "Binghatti Mirage",
    area: "JVC",
    lat: 25.0532,
    lng: 55.2095,
    image: img("p_jvc_04"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 151 5151",
    features: ["50/50 payment plan", "Handover Q2 2026", "Entry-level investor"],
    yearBuilt: 2026,
    status: "available",
  },

  // ----- Palm Jumeirah -----
  {
    id: "p_palm_01",
    title: "5BR Beachfront Villa",
    type: "villa",
    listing: "sale",
    price: 28500000,
    beds: 5,
    baths: 7,
    area_sqft: 7800,
    building: "Garden Homes",
    area: "Palm Jumeirah",
    lat: 25.1135,
    lng: 55.1370,
    image: img("p_palm_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 161 6161",
    features: ["Private beach", "Pool", "Maid + driver rooms", "Skyline view"],
    yearBuilt: 2008,
    status: "available",
  },
  {
    id: "p_palm_02",
    title: "2BR Beach Apartment",
    type: "apartment",
    listing: "sale",
    price: 4750000,
    beds: 2,
    baths: 3,
    area_sqft: 1610,
    building: "Shoreline Apartments",
    area: "Palm Jumeirah",
    lat: 25.1116,
    lng: 55.1408,
    image: img("p_palm_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 171 7171",
    features: ["Direct beach access", "Atlantis view", "Pool"],
    yearBuilt: 2008,
    status: "available",
  },
  {
    id: "p_palm_03",
    title: "3BR Penthouse — Trunk View",
    type: "penthouse",
    listing: "sale",
    price: 14500000,
    beds: 3,
    baths: 4,
    area_sqft: 3850,
    building: "Tiara Residence",
    area: "Palm Jumeirah",
    lat: 25.1108,
    lng: 55.1442,
    image: img("p_palm_03"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 181 8181",
    features: ["Roof terrace", "Sunset view", "Tenanted", "Premium finish"],
    yearBuilt: 2013,
    status: "available",
  },
  {
    id: "p_palm_04",
    title: "4BR Villa for Rent",
    type: "villa",
    listing: "rent",
    price: 850000,
    beds: 4,
    baths: 5,
    area_sqft: 6200,
    building: "Signature Villas Frond G",
    area: "Palm Jumeirah",
    lat: 25.1150,
    lng: 55.1310,
    image: img("p_palm_04"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 191 9191",
    features: ["Private pool", "Beachfront", "Maid + driver rooms"],
    yearBuilt: 2009,
    status: "available",
  },

  // ----- Arabian Ranches -----
  {
    id: "p_ranch_01",
    title: "4BR Townhouse — Quiet Street",
    type: "townhouse",
    listing: "sale",
    price: 4250000,
    beds: 4,
    baths: 5,
    area_sqft: 3400,
    building: "Camelia Cluster",
    area: "Arabian Ranches",
    lat: 25.0455,
    lng: 55.2691,
    image: img("p_ranch_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 212 1212",
    features: ["Family community", "Park view", "Garage 2 cars"],
    yearBuilt: 2014,
    status: "available",
  },
  {
    id: "p_ranch_02",
    title: "5BR Villa — Golf Course View",
    type: "villa",
    listing: "sale",
    price: 7500000,
    beds: 5,
    baths: 6,
    area_sqft: 5100,
    building: "Polo Homes",
    area: "Arabian Ranches",
    lat: 25.0488,
    lng: 55.2728,
    image: img("p_ranch_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 222 1212",
    features: ["Golf view", "Private pool", "Quiet cluster", "School zone"],
    yearBuilt: 2011,
    status: "available",
  },
  {
    id: "p_ranch_03",
    title: "3BR Family Townhouse",
    type: "townhouse",
    listing: "rent",
    price: 195000,
    beds: 3,
    baths: 4,
    area_sqft: 2400,
    building: "Saheel Cluster",
    area: "Arabian Ranches",
    lat: 25.0431,
    lng: 55.2664,
    image: img("p_ranch_03"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 232 3232",
    features: ["Community pool", "School bus stop", "Park nearby"],
    yearBuilt: 2010,
    status: "available",
  },
  {
    id: "p_ranch_04",
    title: "6BR Mansion — Equestrian Estate",
    type: "villa",
    listing: "sale",
    price: 19500000,
    beds: 6,
    baths: 8,
    area_sqft: 12500,
    building: "Polo Homes",
    area: "Arabian Ranches",
    lat: 25.0502,
    lng: 55.2742,
    image: img("p_ranch_04"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 242 4242",
    features: ["12,500 sqft plot", "Pool + tennis", "Staff quarters", "Stables"],
    yearBuilt: 2012,
    status: "available",
  },

  // ----- Hotels -----
  {
    id: "p_hotel_01",
    title: "5★ Hotel Investment — 220 Keys",
    type: "hotel",
    listing: "sale",
    price: 285000000,
    beds: 220, // keys
    baths: 230,
    area_sqft: 185000,
    building: "Downtown Hotel & Residences",
    area: "Downtown Dubai",
    lat: 25.1985,
    lng: 55.2719,
    image: img("p_hotel_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 511 5151",
    features: ["220 keys", "Operator in place", "ADR AED 1,400", "Stable RevPAR"],
    yearBuilt: 2017,
    status: "available",
  },
  {
    id: "p_hotel_02",
    title: "Boutique Hotel for Sale — 48 Keys",
    type: "hotel",
    listing: "sale",
    price: 62000000,
    beds: 48,
    baths: 50,
    area_sqft: 42000,
    building: "Marina Boutique Hotel",
    area: "Dubai Marina",
    lat: 25.0789,
    lng: 55.1412,
    image: img("p_hotel_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 522 5252",
    features: ["48 keys", "Marina view", "Rooftop bar", "Restaurant included"],
    yearBuilt: 2015,
    status: "available",
  },

  // ----- Manufacturing / Industrial -----
  {
    id: "p_indust_01",
    title: "Warehouse — 20,000 sqft Al Quoz",
    type: "warehouse",
    listing: "rent",
    price: 480000,
    beds: 0,
    baths: 2,
    area_sqft: 20000,
    building: "Al Quoz Industrial Area 3",
    area: "Al Quoz",
    lat: 25.1308,
    lng: 55.2236,
    image: img("p_indust_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 611 6161",
    features: ["3-phase power", "Loading dock", "Office mezzanine", "24/7 access"],
    yearBuilt: 2010,
    status: "available",
  },
  {
    id: "p_indust_02",
    title: "Light Manufacturing Unit — DIP",
    type: "warehouse",
    listing: "sale",
    price: 8500000,
    beds: 0,
    baths: 3,
    area_sqft: 32000,
    building: "Dubai Investment Park",
    area: "Dubai Investment Park",
    lat: 24.9874,
    lng: 55.1742,
    image: img("p_indust_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 622 6262",
    features: ["Free zone eligible", "Heavy power", "Office block", "Truck yard"],
    yearBuilt: 2013,
    status: "available",
  },

  // ----- Retail / Shops -----
  {
    id: "p_retail_01",
    title: "Retail Shop — Marina Walk Frontage",
    type: "retail",
    listing: "rent",
    price: 380000,
    beds: 0,
    baths: 1,
    area_sqft: 1450,
    building: "Marina Walk Retail",
    area: "Dubai Marina",
    lat: 25.0795,
    lng: 55.1408,
    image: img("p_retail_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 711 7171",
    features: ["Glass frontage", "F&B-ready", "Promenade footfall", "Outdoor seating"],
    yearBuilt: 2008,
    status: "available",
  },
  {
    id: "p_retail_02",
    title: "Boutique Retail — City Walk",
    type: "retail",
    listing: "rent",
    price: 260000,
    beds: 0,
    baths: 1,
    area_sqft: 980,
    building: "City Walk Phase 2",
    area: "Downtown Dubai",
    lat: 25.2057,
    lng: 55.2622,
    image: img("p_retail_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 722 7272",
    features: ["High footfall district", "AC corridor", "Storage room", "Brand-friendly"],
    yearBuilt: 2018,
    status: "available",
  },
];

// Activity vocabulary the agent uses to filter what shows inside each working zone.
// Each entry has a stable `value` (stored on zones + matched against property.activities)
// and a friendly label + icon for the UI.
export const ACTIVITY_TYPES = [
  { value: "sell",          label: "Sell",          icon: "💰", color: "bg-amber-500/15 text-amber-300 border-amber-500/30" },
  { value: "buy",           label: "Buy",           icon: "🏷️", color: "bg-emerald-500/15 text-emerald-300 border-emerald-500/30" },
  { value: "rent",          label: "Rent",          icon: "📅", color: "bg-cyan-500/15 text-cyan-300 border-cyan-500/30" },
  { value: "airbnb",        label: "Airbnb",        icon: "🏖️", color: "bg-rose-500/15 text-rose-300 border-rose-500/30" },
  { value: "office",        label: "Office",        icon: "💼", color: "bg-blue-500/15 text-blue-300 border-blue-500/30" },
  { value: "hotel",         label: "Hotels",        icon: "🏨", color: "bg-purple-500/15 text-purple-300 border-purple-500/30" },
  { value: "manufacturing", label: "Manufacturing", icon: "🏭", color: "bg-orange-500/15 text-orange-300 border-orange-500/30" },
  { value: "retail",        label: "Retail",        icon: "🛍️", color: "bg-pink-500/15 text-pink-300 border-pink-500/30" },
];

// Derive the activity tags for a property from its listing + type + features.
// This way we don't have to manually tag each mock entry above.
export function activitiesFor(p) {
  const acts = [];
  if (p.type === "office") acts.push("office");
  if (p.type === "hotel") acts.push("hotel");
  if (p.type === "warehouse") acts.push("manufacturing");
  if (p.type === "retail") acts.push("retail");
  // Residential transactions:
  const isResidential = ["apartment", "villa", "townhouse", "studio", "penthouse"].includes(p.type);
  if (isResidential) {
    if (p.listing === "sale") acts.push("sell", "buy");
    if (p.listing === "rent") acts.push("rent");
  } else if (p.listing === "sale" && !acts.includes("sell")) {
    // Commercial properties also support sell/buy.
    acts.push("sell", "buy");
  }
  // Short-term let / Airbnb friendly?
  const features = (p.features || []).join(" ").toLowerCase();
  if (/short[- ]?term|airbnb|holiday/.test(features)) acts.push("airbnb");
  // Studios are commonly Airbnb candidates even without explicit tags.
  if (p.type === "studio" && p.listing === "rent" && !acts.includes("airbnb")) acts.push("airbnb");
  return [...new Set(acts)];
}

// Pre-compute activities on every property so consumers don't need the helper.
PROPERTIES.forEach((p) => { p.activities = activitiesFor(p); });

// Format price in AED with thousands separators and rent suffix.
export function formatPrice(p) {
  if (!p || typeof p.price !== "number") return "—";
  const num = new Intl.NumberFormat("en-AE", { maximumFractionDigits: 0 }).format(p.price);
  return p.listing === "rent" ? `AED ${num}/yr` : `AED ${num}`;
}

export const PROPERTY_AREAS = [
  "Dubai Marina",
  "Downtown Dubai",
  "Business Bay",
  "JVC",
  "Palm Jumeirah",
  "Arabian Ranches",
  "Al Quoz",
  "Dubai Investment Park",
];

export const PROPERTY_TYPES = [
  { value: "apartment",  label: "Apartment"  },
  { value: "villa",      label: "Villa"      },
  { value: "townhouse",  label: "Townhouse"  },
  { value: "studio",     label: "Studio"     },
  { value: "penthouse",  label: "Penthouse"  },
  { value: "office",     label: "Office"     },
  { value: "hotel",      label: "Hotel"      },
  { value: "warehouse",  label: "Warehouse"  },
  { value: "retail",     label: "Retail"     },
];
