// Mock Dubai property dataset for the Agent Hub MVP.
// Realistic-but-fictional listings across six well-known areas.
// Images are served by picsum.photos with a stable seed per property so they
// don't reshuffle on every refresh.

function img(seed) {
  return `https://picsum.photos/seed/${seed}/600/360`;
}

export const PROPERTIES = [
  // ----- Dubai Marina -----
  {
    id: "p_marina_01",
    title: "2BR with Full Marina View",
    type: "apartment",
    listing: "sale",
    price: 2150000,
    beds: 2,
    baths: 2,
    area_sqft: 1240,
    building: "Marina Heights Tower 1",
    area: "Dubai Marina",
    lat: 25.0791,
    lng: 55.1390,
    image: img("p_marina_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 123 4567",
    features: ["Marina view", "Furnished", "Parking", "Pool", "Gym"],
    yearBuilt: 2018,
    status: "available",
  },
  {
    id: "p_marina_02",
    title: "1BR Cozy near Marina Walk",
    type: "apartment",
    listing: "rent",
    price: 95000,
    beds: 1,
    baths: 1,
    area_sqft: 760,
    building: "Princess Tower",
    area: "Dubai Marina",
    lat: 25.0803,
    lng: 55.1437,
    image: img("p_marina_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 234 5678",
    features: ["Partial sea view", "Furnished", "Walk to metro"],
    yearBuilt: 2012,
    status: "available",
  },
  {
    id: "p_marina_03",
    title: "Penthouse 4BR Sky Suite",
    type: "penthouse",
    listing: "sale",
    price: 9500000,
    beds: 4,
    baths: 5,
    area_sqft: 4100,
    building: "Cayan Tower",
    area: "Dubai Marina",
    lat: 25.0823,
    lng: 55.1398,
    image: img("p_marina_03"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 345 6789",
    features: ["Floor-to-ceiling glass", "Private terrace", "3 parking", "Skyline view"],
    yearBuilt: 2014,
    status: "available",
  },
  {
    id: "p_marina_04",
    title: "Studio Investor Special",
    type: "studio",
    listing: "sale",
    price: 850000,
    beds: 0,
    baths: 1,
    area_sqft: 480,
    building: "Marina Diamond 4",
    area: "Dubai Marina",
    lat: 25.0775,
    lng: 55.1422,
    image: img("p_marina_04"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 456 7890",
    features: ["High ROI", "Tenanted", "Near tram"],
    yearBuilt: 2010,
    status: "available",
  },

  // ----- Downtown Dubai -----
  {
    id: "p_downtown_01",
    title: "Burj View 2BR — Premium Finish",
    type: "apartment",
    listing: "sale",
    price: 3950000,
    beds: 2,
    baths: 3,
    area_sqft: 1485,
    building: "Burj Vista 1",
    area: "Downtown Dubai",
    lat: 25.1958,
    lng: 55.2761,
    image: img("p_downtown_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 111 2222",
    features: ["Burj Khalifa view", "Branded finishings", "Concierge", "Pool"],
    yearBuilt: 2019,
    status: "available",
  },
  {
    id: "p_downtown_02",
    title: "Spacious 3BR Family Apartment",
    type: "apartment",
    listing: "rent",
    price: 245000,
    beds: 3,
    baths: 4,
    area_sqft: 2100,
    building: "The Address Residences",
    area: "Downtown Dubai",
    lat: 25.1933,
    lng: 55.2728,
    image: img("p_downtown_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 222 3333",
    features: ["Hotel services", "Fountain view", "Maid's room"],
    yearBuilt: 2017,
    status: "available",
  },
  {
    id: "p_downtown_03",
    title: "1BR City Walk — Modern",
    type: "apartment",
    listing: "sale",
    price: 1850000,
    beds: 1,
    baths: 2,
    area_sqft: 860,
    building: "City Walk Building 4",
    area: "Downtown Dubai",
    lat: 25.2061,
    lng: 55.2628,
    image: img("p_downtown_03"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 333 4444",
    features: ["Walking district", "Boutique retail downstairs", "Smart home"],
    yearBuilt: 2020,
    status: "available",
  },
  {
    id: "p_downtown_04",
    title: "Off-Plan 1BR — Handover 2026",
    type: "apartment",
    listing: "sale",
    price: 1650000,
    beds: 1,
    baths: 1,
    area_sqft: 780,
    building: "Forte 2",
    area: "Downtown Dubai",
    lat: 25.1979,
    lng: 55.2702,
    image: img("p_downtown_04"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 444 5555",
    features: ["Payment plan 60/40", "Post-handover plan", "Opera district"],
    yearBuilt: 2026,
    status: "available",
  },

  // ----- Business Bay -----
  {
    id: "p_bb_01",
    title: "2BR Canal View — High Floor",
    type: "apartment",
    listing: "sale",
    price: 2750000,
    beds: 2,
    baths: 3,
    area_sqft: 1320,
    building: "Damac Maison Bay's Edge",
    area: "Business Bay",
    lat: 25.1862,
    lng: 55.2615,
    image: img("p_bb_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 555 6666",
    features: ["Canal view", "Hotel pool access", "Furnished"],
    yearBuilt: 2018,
    status: "available",
  },
  {
    id: "p_bb_02",
    title: "Studio Investment Unit — Yielding 8%",
    type: "studio",
    listing: "sale",
    price: 720000,
    beds: 0,
    baths: 1,
    area_sqft: 420,
    building: "Executive Bay",
    area: "Business Bay",
    lat: 25.1832,
    lng: 55.2587,
    image: img("p_bb_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 666 7777",
    features: ["Tenanted", "8% gross yield", "Easy exit"],
    yearBuilt: 2014,
    status: "available",
  },
  {
    id: "p_bb_03",
    title: "1BR Modern — Short-Term Friendly",
    type: "apartment",
    listing: "rent",
    price: 110000,
    beds: 1,
    baths: 2,
    area_sqft: 820,
    building: "DAMAC Towers by Paramount",
    area: "Business Bay",
    lat: 25.1875,
    lng: 55.2671,
    image: img("p_bb_03"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 777 8888",
    features: ["Branded interiors", "Short-term let allowed", "Concierge"],
    yearBuilt: 2019,
    status: "available",
  },
  {
    id: "p_bb_04",
    title: "Office Space — Grade A",
    type: "office",
    listing: "rent",
    price: 220000,
    beds: 0,
    baths: 2,
    area_sqft: 1850,
    building: "Bay Square Building 5",
    area: "Business Bay",
    lat: 25.1885,
    lng: 55.2654,
    image: img("p_bb_04"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 888 9999",
    features: ["Fitted out", "Glass partitions", "Parking allocations"],
    yearBuilt: 2015,
    status: "available",
  },

  // ----- JVC (Jumeirah Village Circle) -----
  {
    id: "p_jvc_01",
    title: "1BR Affordable Starter",
    type: "apartment",
    listing: "sale",
    price: 780000,
    beds: 1,
    baths: 2,
    area_sqft: 760,
    building: "Belgravia 2",
    area: "JVC",
    lat: 25.0529,
    lng: 55.2071,
    image: img("p_jvc_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 121 2121",
    features: ["First-time buyer friendly", "Family community", "Park nearby"],
    yearBuilt: 2017,
    status: "available",
  },
  {
    id: "p_jvc_02",
    title: "2BR + Maid Family Apartment",
    type: "apartment",
    listing: "rent",
    price: 95000,
    beds: 2,
    baths: 3,
    area_sqft: 1180,
    building: "Bloom Heights",
    area: "JVC",
    lat: 25.0481,
    lng: 55.2104,
    image: img("p_jvc_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 131 3131",
    features: ["Maid's room", "Built-in kitchen", "Quiet street"],
    yearBuilt: 2020,
    status: "available",
  },
  {
    id: "p_jvc_03",
    title: "3BR Townhouse — Garden",
    type: "townhouse",
    listing: "sale",
    price: 2850000,
    beds: 3,
    baths: 4,
    area_sqft: 2100,
    building: "Nakheel Townhouses",
    area: "JVC",
    lat: 25.0503,
    lng: 55.2042,
    image: img("p_jvc_03"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 141 4141",
    features: ["Private garden", "2 parking", "Community pool"],
    yearBuilt: 2019,
    status: "available",
  },
  {
    id: "p_jvc_04",
    title: "Studio Off-Plan — Payment Plan",
    type: "studio",
    listing: "sale",
    price: 590000,
    beds: 0,
    baths: 1,
    area_sqft: 410,
    building: "Binghatti Mirage",
    area: "JVC",
    lat: 25.0532,
    lng: 55.2095,
    image: img("p_jvc_04"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 151 5151",
    features: ["50/50 payment plan", "Handover Q2 2026", "Entry-level investor"],
    yearBuilt: 2026,
    status: "available",
  },

  // ----- Palm Jumeirah -----
  {
    id: "p_palm_01",
    title: "5BR Beachfront Villa",
    type: "villa",
    listing: "sale",
    price: 28500000,
    beds: 5,
    baths: 7,
    area_sqft: 7800,
    building: "Garden Homes",
    area: "Palm Jumeirah",
    lat: 25.1135,
    lng: 55.1370,
    image: img("p_palm_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 161 6161",
    features: ["Private beach", "Pool", "Maid + driver rooms", "Skyline view"],
    yearBuilt: 2008,
    status: "available",
  },
  {
    id: "p_palm_02",
    title: "2BR Beach Apartment",
    type: "apartment",
    listing: "sale",
    price: 4750000,
    beds: 2,
    baths: 3,
    area_sqft: 1610,
    building: "Shoreline Apartments",
    area: "Palm Jumeirah",
    lat: 25.1116,
    lng: 55.1408,
    image: img("p_palm_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 171 7171",
    features: ["Direct beach access", "Atlantis view", "Pool"],
    yearBuilt: 2008,
    status: "available",
  },
  {
    id: "p_palm_03",
    title: "3BR Penthouse — Trunk View",
    type: "penthouse",
    listing: "sale",
    price: 14500000,
    beds: 3,
    baths: 4,
    area_sqft: 3850,
    building: "Tiara Residence",
    area: "Palm Jumeirah",
    lat: 25.1108,
    lng: 55.1442,
    image: img("p_palm_03"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 181 8181",
    features: ["Roof terrace", "Sunset view", "Tenanted", "Premium finish"],
    yearBuilt: 2013,
    status: "available",
  },
  {
    id: "p_palm_04",
    title: "4BR Villa for Rent",
    type: "villa",
    listing: "rent",
    price: 850000,
    beds: 4,
    baths: 5,
    area_sqft: 6200,
    building: "Signature Villas Frond G",
    area: "Palm Jumeirah",
    lat: 25.1150,
    lng: 55.1310,
    image: img("p_palm_04"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 191 9191",
    features: ["Private pool", "Beachfront", "Maid + driver rooms"],
    yearBuilt: 2009,
    status: "available",
  },

  // ----- Arabian Ranches -----
  {
    id: "p_ranch_01",
    title: "4BR Townhouse — Quiet Street",
    type: "townhouse",
    listing: "sale",
    price: 4250000,
    beds: 4,
    baths: 5,
    area_sqft: 3400,
    building: "Camelia Cluster",
    area: "Arabian Ranches",
    lat: 25.0455,
    lng: 55.2691,
    image: img("p_ranch_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 212 1212",
    features: ["Family community", "Park view", "Garage 2 cars"],
    yearBuilt: 2014,
    status: "available",
  },
  {
    id: "p_ranch_02",
    title: "5BR Villa — Golf Course View",
    type: "villa",
    listing: "sale",
    price: 7500000,
    beds: 5,
    baths: 6,
    area_sqft: 5100,
    building: "Polo Homes",
    area: "Arabian Ranches",
    lat: 25.0488,
    lng: 55.2728,
    image: img("p_ranch_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 222 1212",
    features: ["Golf view", "Private pool", "Quiet cluster", "School zone"],
    yearBuilt: 2011,
    status: "available",
  },
  {
    id: "p_ranch_03",
    title: "3BR Family Townhouse",
    type: "townhouse",
    listing: "rent",
    price: 195000,
    beds: 3,
    baths: 4,
    area_sqft: 2400,
    building: "Saheel Cluster",
    area: "Arabian Ranches",
    lat: 25.0431,
    lng: 55.2664,
    image: img("p_ranch_03"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 232 3232",
    features: ["Community pool", "School bus stop", "Park nearby"],
    yearBuilt: 2010,
    status: "available",
  },
  {
    id: "p_ranch_04",
    title: "6BR Mansion — Equestrian Estate",
    type: "villa",
    listing: "sale",
    price: 19500000,
    beds: 6,
    baths: 8,
    area_sqft: 12500,
    building: "Polo Homes",
    area: "Arabian Ranches",
    lat: 25.0502,
    lng: 55.2742,
    image: img("p_ranch_04"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 242 4242",
    features: ["12,500 sqft plot", "Pool + tennis", "Staff quarters", "Stables"],
    yearBuilt: 2012,
    status: "available",
  },

  // ----- Hotels -----
  {
    id: "p_hotel_01",
    title: "5★ Hotel Investment — 220 Keys",
    type: "hotel",
    listing: "sale",
    price: 285000000,
    beds: 220, // keys
    baths: 230,
    area_sqft: 185000,
    building: "Downtown Hotel & Residences",
    area: "Downtown Dubai",
    lat: 25.1985,
    lng: 55.2719,
    image: img("p_hotel_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 511 5151",
    features: ["220 keys", "Operator in place", "ADR AED 1,400", "Stable RevPAR"],
    yearBuilt: 2017,
    status: "available",
  },
  {
    id: "p_hotel_02",
    title: "Boutique Hotel for Sale — 48 Keys",
    type: "hotel",
    listing: "sale",
    price: 62000000,
    beds: 48,
    baths: 50,
    area_sqft: 42000,
    building: "Marina Boutique Hotel",
    area: "Dubai Marina",
    lat: 25.0789,
    lng: 55.1412,
    image: img("p_hotel_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 522 5252",
    features: ["48 keys", "Marina view", "Rooftop bar", "Restaurant included"],
    yearBuilt: 2015,
    status: "available",
  },

  // ----- Manufacturing / Industrial -----
  {
    id: "p_indust_01",
    title: "Warehouse — 20,000 sqft Al Quoz",
    type: "warehouse",
    listing: "rent",
    price: 480000,
    beds: 0,
    baths: 2,
    area_sqft: 20000,
    building: "Al Quoz Industrial Area 3",
    area: "Al Quoz",
    lat: 25.1308,
    lng: 55.2236,
    image: img("p_indust_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 611 6161",
    features: ["3-phase power", "Loading dock", "Office mezzanine", "24/7 access"],
    yearBuilt: 2010,
    status: "available",
  },
  {
    id: "p_indust_02",
    title: "Light Manufacturing Unit — DIP",
    type: "warehouse",
    listing: "sale",
    price: 8500000,
    beds: 0,
    baths: 3,
    area_sqft: 32000,
    building: "Dubai Investment Park",
    area: "Dubai Investment Park",
    lat: 24.9874,
    lng: 55.1742,
    image: img("p_indust_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 622 6262",
    features: ["Free zone eligible", "Heavy power", "Office block", "Truck yard"],
    yearBuilt: 2013,
    status: "available",
  },

  // ----- Retail / Shops -----
  {
    id: "p_retail_01",
    title: "Retail Shop — Marina Walk Frontage",
    type: "retail",
    listing: "rent",
    price: 380000,
    beds: 0,
    baths: 1,
    area_sqft: 1450,
    building: "Marina Walk Retail",
    area: "Dubai Marina",
    lat: 25.0795,
    lng: 55.1408,
    image: img("p_retail_01"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 711 7171",
    features: ["Glass frontage", "F&B-ready", "Promenade footfall", "Outdoor seating"],
    yearBuilt: 2008,
    status: "available",
  },
  {
    id: "p_retail_02",
    title: "Boutique Retail — City Walk",
    type: "retail",
    listing: "rent",
    price: 260000,
    beds: 0,
    baths: 1,
    area_sqft: 980,
    building: "City Walk Phase 2",
    area: "Downtown Dubai",
    lat: 25.2057,
    lng: 55.2622,
    image: img("p_retail_02"),
    agent: "Eshel Properties",
    agentPhone: "+971 50 722 7272",
    features: ["High footfall district", "AC corridor", "Storage room", "Brand-friendly"],
    yearBuilt: 2018,
    status: "available",
  },

  // ----- Jumeirah / Al Bada'a (covers Al Wasl / Bur Dubai picks) -----
  { id: "p_jum_01", title: "Charming 2BR Jumeirah Apartment", type: "apartment", listing: "rent", price: 145000, beds: 2, baths: 2, area_sqft: 1100, building: "Al Bada'a Residence", area: "Jumeirah", lat: 25.2068, lng: 55.2745, image: img("p_jum_01"), agent: "Eshel Properties", agentPhone: "+971 50 311 1011", features: ["Mature neighbourhood", "Walk to beach", "Furnished"], yearBuilt: 2008, status: "available" },
  { id: "p_jum_02", title: "Detached 4BR Villa — Quiet Street", type: "villa", listing: "sale", price: 8900000, beds: 4, baths: 5, area_sqft: 4800, building: "Jumeirah Villas", area: "Jumeirah", lat: 25.2105, lng: 55.2618, image: img("p_jum_02"), agent: "Eshel Properties", agentPhone: "+971 50 311 2022", features: ["Private garden", "Pool", "Maid's room", "Walk to City Walk"], yearBuilt: 2005, status: "available" },
  { id: "p_jum_03", title: "Studio Holiday Home", type: "studio", listing: "rent", price: 78000, beds: 0, baths: 1, area_sqft: 460, building: "Jumeirah 1 Boutique", area: "Jumeirah", lat: 25.2050, lng: 55.2698, image: img("p_jum_03"), agent: "Eshel Properties", agentPhone: "+971 50 311 3033", features: ["Short-term let allowed", "Renovated", "Walk to beach"], yearBuilt: 2010, status: "available" },
  { id: "p_jum_04", title: "Heritage 3BR Townhouse", type: "townhouse", listing: "sale", price: 5200000, beds: 3, baths: 4, area_sqft: 2700, building: "Bada'a Townhomes", area: "Jumeirah", lat: 25.2078, lng: 55.2772, image: img("p_jum_04"), agent: "Eshel Properties", agentPhone: "+971 50 311 4044", features: ["Renovated", "Private garden", "School zone"], yearBuilt: 2003, status: "available" },
  { id: "p_jum_05", title: "Beachfront 5★ Hotel Suite", type: "hotel", listing: "rent", price: 425000, beds: 0, baths: 2, area_sqft: 1200, building: "Jumeirah Beach Hotel Annexe", area: "Jumeirah", lat: 25.2095, lng: 55.2655, image: img("p_jum_05"), agent: "Eshel Properties", agentPhone: "+971 50 311 5055", features: ["Beach access", "Daily housekeeping", "Branded service"], yearBuilt: 2014, status: "available" },

  // ----- DIFC -----
  { id: "p_difc_01", title: "1BR DIFC Loft", type: "apartment", listing: "sale", price: 2350000, beds: 1, baths: 2, area_sqft: 950, building: "Index Tower", area: "DIFC", lat: 25.2125, lng: 55.2782, image: img("p_difc_01"), agent: "Eshel Properties", agentPhone: "+971 50 411 1011", features: ["High ceiling", "Skyline view", "Metro adjacent"], yearBuilt: 2015, status: "available" },
  { id: "p_difc_02", title: "Grade A Office — Mid Floor", type: "office", listing: "rent", price: 380000, beds: 0, baths: 3, area_sqft: 2600, building: "Gate Village 4", area: "DIFC", lat: 25.2135, lng: 55.2810, image: img("p_difc_02"), agent: "Eshel Properties", agentPhone: "+971 50 411 2022", features: ["Fitted out", "Boardroom", "Reception desk"], yearBuilt: 2010, status: "available" },
  { id: "p_difc_03", title: "Penthouse 3BR — DIFC", type: "penthouse", listing: "sale", price: 14500000, beds: 3, baths: 5, area_sqft: 3850, building: "Park Towers", area: "DIFC", lat: 25.2148, lng: 55.2795, image: img("p_difc_03"), agent: "Eshel Properties", agentPhone: "+971 50 411 3033", features: ["360° view", "Private lift", "Branded interiors"], yearBuilt: 2017, status: "available" },

  // ----- JLT (Jumeirah Lake Towers) -----
  { id: "p_jlt_01", title: "Lake View 1BR", type: "apartment", listing: "sale", price: 1250000, beds: 1, baths: 2, area_sqft: 880, building: "Goldcrest Views 2", area: "JLT", lat: 25.0688, lng: 55.1402, image: img("p_jlt_01"), agent: "Eshel Properties", agentPhone: "+971 50 511 1011", features: ["Lake view", "Metro 5 min walk", "Furnished"], yearBuilt: 2013, status: "available" },
  { id: "p_jlt_02", title: "Studio High Yield", type: "studio", listing: "sale", price: 680000, beds: 0, baths: 1, area_sqft: 440, building: "Cluster Y", area: "JLT", lat: 25.0721, lng: 55.1431, image: img("p_jlt_02"), agent: "Eshel Properties", agentPhone: "+971 50 511 2022", features: ["Tenanted", "8.5% yield", "Investor-friendly"], yearBuilt: 2011, status: "available" },
  { id: "p_jlt_03", title: "2BR Family + Maid", type: "apartment", listing: "rent", price: 130000, beds: 2, baths: 3, area_sqft: 1320, building: "Saba 2", area: "JLT", lat: 25.0703, lng: 55.1378, image: img("p_jlt_03"), agent: "Eshel Properties", agentPhone: "+971 50 511 3033", features: ["Maid's room", "Lake view", "Family community"], yearBuilt: 2009, status: "available" },

  // ----- Dubai Hills Estate -----
  { id: "p_hills_01", title: "4BR Villa — Golf Course View", type: "villa", listing: "sale", price: 7400000, beds: 4, baths: 5, area_sqft: 4200, building: "Maple 1", area: "Dubai Hills", lat: 25.1037, lng: 55.2618, image: img("p_hills_01"), agent: "Eshel Properties", agentPhone: "+971 50 611 1011", features: ["Golf view", "Private garden", "Park nearby"], yearBuilt: 2020, status: "available" },
  { id: "p_hills_02", title: "3BR Townhouse — New Build", type: "townhouse", listing: "sale", price: 3450000, beds: 3, baths: 4, area_sqft: 2400, building: "Sidra 3", area: "Dubai Hills", lat: 25.1062, lng: 55.2655, image: img("p_hills_02"), agent: "Eshel Properties", agentPhone: "+971 50 611 2022", features: ["School zone", "Park-facing", "Community pool"], yearBuilt: 2022, status: "available" },
  { id: "p_hills_03", title: "2BR Apartment — Park View", type: "apartment", listing: "rent", price: 165000, beds: 2, baths: 3, area_sqft: 1380, building: "Park Point", area: "Dubai Hills", lat: 25.1085, lng: 55.2580, image: img("p_hills_03"), agent: "Eshel Properties", agentPhone: "+971 50 611 3033", features: ["Park view", "Mall walk", "Concierge"], yearBuilt: 2021, status: "available" },

  // ----- Mirdif -----
  { id: "p_mir_01", title: "5BR Family Villa", type: "villa", listing: "sale", price: 4250000, beds: 5, baths: 6, area_sqft: 4800, building: "Mirdif Villas", area: "Mirdif", lat: 25.2208, lng: 55.4198, image: img("p_mir_01"), agent: "Eshel Properties", agentPhone: "+971 50 711 1011", features: ["Spacious plot", "Quiet area", "Family community"], yearBuilt: 2008, status: "available" },
  { id: "p_mir_02", title: "3BR Townhouse — Mirdif Hills", type: "townhouse", listing: "rent", price: 175000, beds: 3, baths: 4, area_sqft: 2100, building: "Janayen Avenue", area: "Mirdif", lat: 25.2275, lng: 55.4255, image: img("p_mir_02"), agent: "Eshel Properties", agentPhone: "+971 50 711 2022", features: ["Newly built", "Pool", "Mall walk"], yearBuilt: 2020, status: "available" },

  // ----- Al Barsha -----
  { id: "p_bar_01", title: "1BR Mall of Emirates Walk", type: "apartment", listing: "sale", price: 1050000, beds: 1, baths: 2, area_sqft: 820, building: "Al Barsha 1 Heights", area: "Al Barsha", lat: 25.1110, lng: 55.2002, image: img("p_bar_01"), agent: "Eshel Properties", agentPhone: "+971 50 811 1011", features: ["Mall walk", "Metro 8 min", "Furnished"], yearBuilt: 2014, status: "available" },
  { id: "p_bar_02", title: "3BR Family Villa", type: "villa", listing: "rent", price: 215000, beds: 3, baths: 4, area_sqft: 3100, building: "Al Barsha Villas", area: "Al Barsha", lat: 25.1148, lng: 55.2055, image: img("p_bar_02"), agent: "Eshel Properties", agentPhone: "+971 50 811 2022", features: ["Garden", "Quiet street", "School zone"], yearBuilt: 2010, status: "available" },

  // ----- Bur Dubai -----
  { id: "p_bur_01", title: "2BR Heritage Apartment", type: "apartment", listing: "rent", price: 88000, beds: 2, baths: 2, area_sqft: 1050, building: "Mankhool Residence", area: "Bur Dubai", lat: 25.2522, lng: 55.2950, image: img("p_bur_01"), agent: "Eshel Properties", agentPhone: "+971 50 911 1011", features: ["Old Dubai charm", "Metro adjacent", "Souk walk"], yearBuilt: 2002, status: "available" },
  { id: "p_bur_02", title: "Studio Affordable", type: "studio", listing: "rent", price: 42000, beds: 0, baths: 1, area_sqft: 380, building: "Al Karama Plaza", area: "Bur Dubai", lat: 25.2495, lng: 55.3025, image: img("p_bur_02"), agent: "Eshel Properties", agentPhone: "+971 50 911 2022", features: ["Budget-friendly", "Metro walk", "Furnished"], yearBuilt: 1998, status: "available" },
  { id: "p_bur_03", title: "Retail Shop — Souk Street", type: "retail", listing: "rent", price: 95000, beds: 0, baths: 1, area_sqft: 650, building: "Bur Dubai Souk", area: "Bur Dubai", lat: 25.2575, lng: 55.2935, image: img("p_bur_03"), agent: "Eshel Properties", agentPhone: "+971 50 911 3033", features: ["High footfall", "Tourist area", "Storage"], yearBuilt: 2000, status: "available" },

  // ----- Karama -----
  { id: "p_kar_01", title: "1BR Affordable Apartment", type: "apartment", listing: "rent", price: 55000, beds: 1, baths: 1, area_sqft: 680, building: "Karama Centre", area: "Karama", lat: 25.2480, lng: 55.3070, image: img("p_kar_01"), agent: "Eshel Properties", agentPhone: "+971 50 121 1011", features: ["Walk to metro", "Family-friendly", "Park adjacent"], yearBuilt: 2003, status: "available" },
  { id: "p_kar_02", title: "Retail Unit — Foodie Strip", type: "retail", listing: "rent", price: 78000, beds: 0, baths: 1, area_sqft: 540, building: "Karama Eats", area: "Karama", lat: 25.2455, lng: 55.3092, image: img("p_kar_02"), agent: "Eshel Properties", agentPhone: "+971 50 121 2022", features: ["F&B district", "High footfall", "Kitchen ready"], yearBuilt: 2005, status: "available" },

  // ----- Deira -----
  { id: "p_deira_01", title: "2BR Family Apartment", type: "apartment", listing: "sale", price: 720000, beds: 2, baths: 2, area_sqft: 1180, building: "Al Rigga Towers", area: "Deira", lat: 25.2735, lng: 55.3245, image: img("p_deira_01"), agent: "Eshel Properties", agentPhone: "+971 50 131 1011", features: ["Metro walk", "Affordable", "Established neighbourhood"], yearBuilt: 2001, status: "available" },
  { id: "p_deira_02", title: "Studio Investor Pick", type: "studio", listing: "sale", price: 395000, beds: 0, baths: 1, area_sqft: 410, building: "Salahuddin Plaza", area: "Deira", lat: 25.2710, lng: 55.3198, image: img("p_deira_02"), agent: "Eshel Properties", agentPhone: "+971 50 131 2022", features: ["Tenanted", "Strong yield", "Metro adjacent"], yearBuilt: 2004, status: "available" },
];

// Activity vocabulary the agent uses to filter what shows inside each working zone.
// Each entry has a stable `value` (stored on zones + matched against property.activities)
// and a friendly label + icon for the UI.
export const ACTIVITY_TYPES = [
  { value: "sell",          label: "Sell",          icon: "💰", color: "bg-amber-500/15 text-amber-300 border-amber-500/30" },
  { value: "buy",           label: "Buy",           icon: "🏷️", color: "bg-emerald-500/15 text-emerald-300 border-emerald-500/30" },
  { value: "rent",          label: "Rent",          icon: "📅", color: "bg-cyan-500/15 text-cyan-300 border-cyan-500/30" },
  { value: "airbnb",        label: "Airbnb",        icon: "🏖️", color: "bg-rose-500/15 text-rose-300 border-rose-500/30" },
  { value: "office",        label: "Office",        icon: "💼", color: "bg-blue-500/15 text-blue-300 border-blue-500/30" },
  { value: "hotel",         label: "Hotels",        icon: "🏨", color: "bg-purple-500/15 text-purple-300 border-purple-500/30" },
  { value: "manufacturing", label: "Manufacturing", icon: "🏭", color: "bg-orange-500/15 text-orange-300 border-orange-500/30" },
  { value: "retail",        label: "Retail",        icon: "🛍️", color: "bg-pink-500/15 text-pink-300 border-pink-500/30" },
];

// Derive the activity tags for a property from its listing + type + features.
// This way we don't have to manually tag each mock entry above.
export function activitiesFor(p) {
  const acts = [];
  if (p.type === "office") acts.push("office");
  if (p.type === "hotel") acts.push("hotel");
  if (p.type === "warehouse") acts.push("manufacturing");
  if (p.type === "retail") acts.push("retail");
  // Residential transactions:
  const isResidential = ["apartment", "villa", "townhouse", "studio", "penthouse"].includes(p.type);
  if (isResidential) {
    if (p.listing === "sale") acts.push("sell", "buy");
    if (p.listing === "rent") acts.push("rent");
  } else if (p.listing === "sale" && !acts.includes("sell")) {
    // Commercial properties also support sell/buy.
    acts.push("sell", "buy");
  }
  // Short-term let / Airbnb friendly?
  const features = (p.features || []).join(" ").toLowerCase();
  if (/short[- ]?term|airbnb|holiday/.test(features)) acts.push("airbnb");
  // Studios are commonly Airbnb candidates even without explicit tags.
  if (p.type === "studio" && p.listing === "rent" && !acts.includes("airbnb")) acts.push("airbnb");
  return [...new Set(acts)];
}

// Pre-compute activities on every property so consumers don't need the helper.
PROPERTIES.forEach((p) => { p.activities = activitiesFor(p); });

// Format price in AED with thousands separators and rent suffix.
export function formatPrice(p) {
  if (!p || typeof p.price !== "number") return "—";
  const num = new Intl.NumberFormat("en-AE", { maximumFractionDigits: 0 }).format(p.price);
  return p.listing === "rent" ? `AED ${num}/yr` : `AED ${num}`;
}

export const PROPERTY_AREAS = [
  "Dubai Marina",
  "Downtown Dubai",
  "Business Bay",
  "JVC",
  "Palm Jumeirah",
  "Arabian Ranches",
  "Al Quoz",
  "Dubai Investment Park",
  "Jumeirah",
  "DIFC",
  "JLT",
  "Dubai Hills",
  "Mirdif",
  "Al Barsha",
  "Bur Dubai",
  "Karama",
  "Deira",
];

export const PROPERTY_TYPES = [
  { value: "apartment",  label: "Apartment"  },
  { value: "villa",      label: "Villa"      },
  { value: "townhouse",  label: "Townhouse"  },
  { value: "studio",     label: "Studio"     },
  { value: "penthouse",  label: "Penthouse"  },
  { value: "office",     label: "Office"     },
  { value: "hotel",      label: "Hotel"      },
  { value: "warehouse",  label: "Warehouse"  },
  { value: "retail",     label: "Retail"     },
];
